/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IECPDKSAP_Announcer,
  IECPDKSAP_AnnouncerInterface,
} from "../../interface/IECPDKSAP_Announcer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "schemeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "stealthAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "ephemeralPubKey",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "Announcement",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_R",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_viewTag",
        type: "bytes",
      },
    ],
    name: "ethSentWithoutProxy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_stealthAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_R",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_viewTag",
        type: "bytes",
      },
    ],
    name: "sendEthViaProxy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IECPDKSAP_Announcer__factory {
  static readonly abi = _abi;
  static createInterface(): IECPDKSAP_AnnouncerInterface {
    return new Interface(_abi) as IECPDKSAP_AnnouncerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IECPDKSAP_Announcer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IECPDKSAP_Announcer;
  }
}
