/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ECPDKSAP_Announcer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECPDKSAP_Announcer__factory>;
    getContractFactory(
      name: "ECPDKSAP_MetaAddressRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECPDKSAP_MetaAddressRegistry__factory>;
    getContractFactory(
      name: "IECPDKSAP_Announcer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IECPDKSAP_Announcer__factory>;
    getContractFactory(
      name: "IECPDKSAP_MetaAddressRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IECPDKSAP_MetaAddressRegistry__factory>;
    getContractFactory(
      name: "IERC5564Announcer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5564Announcer__factory>;

    getContractAt(
      name: "ECPDKSAP_Announcer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ECPDKSAP_Announcer>;
    getContractAt(
      name: "ECPDKSAP_MetaAddressRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ECPDKSAP_MetaAddressRegistry>;
    getContractAt(
      name: "IECPDKSAP_Announcer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IECPDKSAP_Announcer>;
    getContractAt(
      name: "IECPDKSAP_MetaAddressRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IECPDKSAP_MetaAddressRegistry>;
    getContractAt(
      name: "IERC5564Announcer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5564Announcer>;

    deployContract(
      name: "ECPDKSAP_Announcer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECPDKSAP_Announcer>;
    deployContract(
      name: "ECPDKSAP_MetaAddressRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECPDKSAP_MetaAddressRegistry>;
    deployContract(
      name: "IECPDKSAP_Announcer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IECPDKSAP_Announcer>;
    deployContract(
      name: "IECPDKSAP_MetaAddressRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IECPDKSAP_MetaAddressRegistry>;
    deployContract(
      name: "IERC5564Announcer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5564Announcer>;

    deployContract(
      name: "ECPDKSAP_Announcer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECPDKSAP_Announcer>;
    deployContract(
      name: "ECPDKSAP_MetaAddressRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECPDKSAP_MetaAddressRegistry>;
    deployContract(
      name: "IECPDKSAP_Announcer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IECPDKSAP_Announcer>;
    deployContract(
      name: "IECPDKSAP_MetaAddressRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IECPDKSAP_MetaAddressRegistry>;
    deployContract(
      name: "IERC5564Announcer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5564Announcer>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
